"use strict";
const MKey_COLOR_SLIDERS = UID++;
const commands = (()=>{
    var i = 1;
    /*   NOTE IMPORTANT LOCATION OF COMMAND MATTERS. MUST BE BETWEEN markers for associated handler */
    return {
        pannelClicked: i++,
        displayOnly: i++,
        testButton: i++,


        floatingPannelCommandsStart: i++,
        floatingPannelClose: i++,
        floatingPannelMinMax: i ++,
        floatingPannelCommandsEnd: i++,




        sysCommandsStart: i++, // just a marker
        // general commands without a defined UI (currently 2020)
        sysShowFileHistory: i++,
        sysResetAll: i++,
        sysResetAllSilent: i++,
        sysSaveSettingsAsJSON: i++,
        sysSaveSettingsAsJSONWithDescriptions: i++,
        sysSaveCommandBuffer: i++,
        sysHideUIToggle: i++,
        sysHideUIFull: i++,   // does not leave size bar
        sysShowUITemp: i++,
        sysShowTimeBarTemp: i++,
        sysGlobalEscape: i++, // This is issued to all handlers and is triggered by the user hitting the ESC key
        sysUp: i++,
        sysDown: i++,
        csysForceRightButton: i++,
        sysCommandManagerQueueCallback: i++,
        sysCommandsEnd: i++, // just a marker

        //==============================================================================
        lightBoxStart: i++,
        lightBoxToggle: i++,
        lightBoxCyclePastEnds: i++,

        lightBoxTimeOffsetFirst: i++,
        lightBoxTimeOffsetLast: (i += 20, i++),
        lightBoxLayerFirst: i++,
        lightBoxLayerLast: (i += 10, i++),
        lightBoxEnd: i++,
        //==============================================================================
        colors: i++, // just a marker
        swatchLow: i++,
        swatch1: i++,
        swatch3: i++,
        swatch4: i++,
        swatch5: i++,
        swatch6: i++,
        swatch7: i++,
        swatch8: i++,
        swatch9: i++,
        swatch10: i++,
        swatch11: i++,
        swatch12: i++,
        swatch13: i++,
        swatch14: i++,
        swatch15: i++,
        swatch16: i++,
        swatch17: i++,
        swatch18: i++,
        swatch19: i++,
        swatch20: i++,
        swatch21: i++,
        swatch22: i++,
        swatchHigh: i++,
        scrollSwatchLeft: i++,
        scrollSwatchRight: i++,
        drawModeExtra1: i++,
        drawModeExtra2: i++,
        drawModeExtra3: i++,
        drawModeExtra4: i++,
        drawModeExtra5: i++,
        drawModeExtra6: i++,
        drawModeExtra7: i++,
        drawModeExtra8: i++,
        drawModeExtra9: i++,
        drawModeExtra10: i++,
        drawModeExtra11: i++,
        drawModeExtra12: i++,
        drawModeExtra13: i++,
        drawModeExtra14: i++,

        colorsPrevSwatch: i++,
        colorsNextSwatch: i++,
        colorsDarker: i++,
        colorsLighter: i++,
        colorsHueDown: i++,
        colorsHueUp: i++,
        colorsSatUp: i++,
        colorsSatDown: i++,


        mainColor: i++,
        secondColor: i++,
        swatchToMainColor: i++,
        redSlider: i++,
        greenSlider: i++,
        blueSlider: i++,
        alphaSlider: i++,
        hueSlider: i++,
        satSlider: i++,
        lumSlider: i++,
        alphaSlider: i++,
        colorPicker: i++,
        colorPickerCommit: i++,
        setBackgroundColor: i++,
        setSpriteColor: i++,
        setImageBGColor: i++,
        setSnapGridColor: i++,
        drawModeOver: i++,
        drawModeErase: i++,
        drawModeOntop: i++,
        drawModeBehind: i++,
        drawModeOverB: i++,
        drawModeEraseB: i++,
        drawModeOntopB: i++,
        drawModeBehindB: i++,
        drawModeLighter: i++,
        drawModeDarker: i++,
        drawModeLighterB: i++,
        drawModeDarkerB: i++,
        drawModeLast: i++,  // just a marker
        useHSLColorRange: i++,
        setPalletDefault: i++,
        colorsEnd: i++,   // just a marker
        //==============================================================================
        // Filter dialogs
        dialogRed: i++,
        dialogGreen: i++,
        dialogBlue: i++,
        dialogAlpha: i++,
        dialogHue: i++,
        dialogSat: i++,
        dialogLum: i++,
        dialogXPos: i++,
        dialogYPos: i++,
        dialogShadowBlur: i++,
        dialogShadowUseMain: i++,
        dialogShadowUseSecond: i++,
        dialogBlur: i++,
        dialogBlurType: i++,
        //==============================================================================
        // command quick dialog command range
        quickDialogBase : i,
        quickDialogTop : (i += 1000, i++),
        quickDialogExtras: i++,
        quickDialogExtrasTop : (i += 10, i++),
        //==============================================================================
        media: i++,
        mediaItem: i++,
        mediaSaveJpg: i++,
        mediaSavePng: i++,
        mediaImageToClipboard: i++,
        mediaSelectFromSelected: i++,
        mediaDeleteImage: i++,
        mediaReorder: i++,
        mediaSelectInvert : i++,
        mediaSelectAll: i++,
        spritesToDrawable: i++,
        mediaAddToWorkspace: i++,
        mediaSetToCutBuffer: i++,
        mediaGetFromCutBuffer: i++,
        mediaCutBufferUpdate: i++,
        mediaSetVideoSrc: i++,
        mediaSetSpriteImage: i++,
        mediaImageZoomSendToTab: i++,
        mediaEnd: i++,   // just a marker
        //==============================================================================
        sprites: i++,
        spritesItem: i++,
        spritesSelectAll: i++,
        spritesUnselectAll: i++,
        spritesSelectInvert: i++,
        spritesShowSelected: i++,
		spritesOrderUp: i++,
		spritesOrderDown: i++,
        saveForUndo: i++,


        // spritesToDrawable: i++,
        spritesToDrawOn: i++,
        spritesToDrawOff: i++,
        spritesToggleToDraw: i++,
        spritesGroup: i++,
        spritesUngroup: i++,
        spritesOpenGroup: i++,
        spritesCloseGroup: i++,
        spritesCollect: i++,
        spritesUncollect: i++,
        spritesShowCollections: i++,
        spritesShowGroups: i++,
        spritesShowLayers: i++,
        spritesShowSprites: i++,

        spritesSelectedToClipboard: i++,
        spritesSaveSelected: i++,
        spritesSaveSelectedLocal: i++,
        spritesSaveAll: i++,
        spritesSaveAllLocal: i ++,
        spritesLoadFromLocal: i ++,
        spritesRemember: i++,
        spritesRecall: i++,
        spritesEnd: i++,   // just a marker
        //==============================================================================
        extras: i++,
        extrasFold: i++,
        extrasItem: i++,
        extrasOption1: i++,
        extrasOption2: i++,
        extrasOption3: i++,
        extrasOption4: i++,
        extrasCustom: i++,
        extrasEnd  : (i += 100000, i++),   // just a marker
        //==============================================================================
        webGLFiltersStart: i++,  // just a marker
        webGLFilterClose: i++,
        webGLFilterApply: i++,
        webGLFilterPreview: i++,
		webGLFilterReset: i++,
		webGLFilterCommandLineString: i++,
        webGLFilterCancel: i++,
        webGLFilterUpdateDialog: i++,
        webGLFilterArgsBase: i++,


        webGLFiltersEnd  : (i += 100000, i++),   // just a marker
        //==============================================================================
        edSpr: i++,

        edSprDelete: i++,
        edSprCopy: i++,
        edSprCopyAnim: i++,
        edSprImageCopy: i++,
        edSprClone: i++,
        edSprCloneAnim: i++,
        edSprAnimImgCopyInsert: i++,
        edSprAnimImgCopyAdd: i++,
        edSprAnimImgCopyReplace: i++,
        edSprAnimImgInsert: i++,
        edSprAnimImgAdd: i++,
        edSprAnimImgReplace: i++,
        edSprUpdateAnimPath: i++,
        edSprTop: i++,
        edSprBot: i++,
        edSprUp: i++,
        edSprDown: i++,
        edSprDouble: i++,
        edSprHalf: i++,
        edSprDoubleHor: i++,
        edSprHalfHor: i++,
        edSprDoubleVer: i++,
        edSprHalfVert: i++,
        edSprClipboardCopy: i++,
        edSprClipboardPaste: i++,
        edSprGroupSelected: i++,
        edSprGroupClose: i++,
        edSprUngroupSelected: i++,
        edSprOpenSelectedGroup: i++,
        edSprOpenCopyGroup: i++,
        edSprCreateCutter: i++,
        edSprCreateDraw: i++,
        edSprCreateGridSprite: i++,
        edSprCreateGrid: i++,
        edSprCreateVanish: i++,
        edSprCreateVanishB: i++,
        edSprCreateMarker: i++,
        edSprCreatePallet: i++,
        edSprCreateFunctionLink: i++,
        edSprCreateText: i++,

        edSprCreateShape: i++,
        edSprCreateShape_Circle: i++,
        edSprCreateShape_Ellipse: i++,
        edSprCreateShape_Square: i++,
        edSprCreateShape_Rectangle: i++,
        edSprCreateShape_Cone: i++,
        edSprCreateShape_Polygon: i++,
        edSprCreateShape_Poly: i++,
        edSprCreateShape_Star: i++,
        edSprCreateShape_Gear: i++,
        edSprCreateShape_CompoundShape: i++,
        edSprCreateShape_CompoundCircle: i++,
        edSprCreateShape_CompoundLine: i++,
        edSprCreateShape_Arrow: i++,
        edSprCreateShape_AngleArrow: i++,
        edSprCreateShape_Vector: i++,
        edSprCreateShape_Tube: i++,
        edSprCreateShape_Sphere: i++,
        edSprSelectTree: i++,
        edSprOrderFunctionLinks: i++,
        edSprToggleOutline: i++,
        edSprUpdateAll: i++,
		edSprNextSubSprite: i ++,
		edSprPrevSubSprite: i ++,
        edSprMirrorVer: i++,
        edSprMirrorHor: i++,
        edSprRotCW: i++,
        edSprRotCCW: i++,
        edSprAlignTop: i++,
        edSprAlignMid: i++,
        edSprAlignBot: i++,
        edSprAlignLeft: i++,
        edSprAlignCenter: i++,
        edSprAlignRight: i++,
        edSprAlignRotate: i++,
        edSprClearSelected: i++,
        edSprVideoCaptureFrame: i++,
        edSprPattern: i++,
        edSprSnapTo: i++,
        edSprLiveCapture: i++,
        edSprCaptureSource: i++,
        edSprVideoCapture: i++,
        edSprLiveCaptureVideo: i++,
        edSprSpaceVer: i++,
        edSprSpaceHor: i++,
        edSprResetView: i++,
        edSprResetViewFit: i++,
        edSprToggleViewSprite: i++,
        edSprSetViewSprite: i++,
        edSprJoinCompoundShape: i++,
        edSpriteToggleLookAt: i++,
        edSpriteToggleAttachTo: i++,
        edSpriteToggleLinkedTo: i++,
        edSpriteToggleAttachScale: i++,
        edSpriteToggleAttachPattern: i++,
        edSpriteToggleAttachmentScale: i++,
        edSpriteToggleAttachRotate: i++,
        edSpriteToggleXYPositionLocks: i++,
        edSpriteToggleIKChain: i++,
        edSprToggleSpriteAsPaintSrc: i++,
        edSprLockUI: i++,
        edSpriteToggleShow: i++,
        edSpriteHide: i++,
        edSpriteHideFromRenderToggle: i++,
        edSpriteShow: i++,
        edSpriteAttachFuncInput: i++,
        edSpriteAttachFuncOutput: i++,
        edSpriteResetFunctionLinks: i++,
        edSpriteResetAllFunctionLinks: i++,
        edSpriteActivateFunctionLinks: i++,
        edSpriteDeActivateFunctionLinks: i++,
        edSpriteSyncFunctionLinks: i++,
        edSpriteFreeSyncFunctionLinks: i++,

        edSpriteAddLocator: i++,
        edSpriteToggleTimeline: i++,
        edSprFitToo: i++,
        edSprResetScale: i++,
        edSprResetRot: i++,
        edSprClip: i++,
        edSprPad: i++,
        edSprDrawing: i++,
        edSprSmooth: i++,
        edSprSnapToggle: i++,
        edSprShowGrid: i++,
        edSprGridSnap1: i++, // 1,2,4,8,16,24, 32, 48,64,96,128,192,256
        edSprGridSnapLast: (i += 16, i++),
        edSprBigPlayPause: i++,
        edSprUpdateUI: i++,
        edSprUndo: i++,
        edSprRedo: i++,
        edSprRevertImage: i++,
        edSprStoreImage: i++,
        edSprComp0: i++,
        edSprComp1: i++,
        edSprComp2: i++,
        edSprComp3: i++,
        edSprComp4: i++,
        edSprComp5: i++,
        edSprComp6: i++,
        edSprComp7: i++,
        edSprComp8: i++,
        edSprComp9: i++,
        edSprComp10: i++,
        edSprComp11: i++,
        edSprComp12: i++,
        edSprComp13: i++,
        edSprComp14: i++,
        edSprComp15: i++,
        edSprComp16: i++,
        edSprComp17: i++,
        edSprComp18: i++,
        edSprComp19: i++,
        edSprComp20: i++,
        edSprComp21: i++,
        edSprComp22: i++,
        edSprComp23: i++,
        edSprComp24: i++,
        edSprFill  : i++,
        edSprStroke: i++,
        edSprAlpha: i++,
        edSprEnd: i++,   // just a marker
        //==============================================================================
        paintStart: i++,  // just a marker
        paintCutBufferUpdate: i++,
        paintDrawTypesStart: i++,
        paintLine: i++,
        paintCircle: i++,
        paintRectangle: i++,
        paintCurve: i++,
        paintSpray: i++,
        paintPoints: i++,
        paintImageSpray: i ++,
        paintImage: i++,
        paintFloodFill: i++,
        paintBrissle: i++,
        paintBrissleB: i++,
        paintBrissleC: i++,
        paintCutter: i++,
        paintMagicCutter: i++,
        paintDrawTypesEnd: i++,  // just a marker
        paintSpecialBrushMode : i, // this and paintSBM_1 share ID
        paintSBM_1: i ++,
        paintSBM_2: i ++,
        paintSBM_3: i ++,
        paintSBM_4: i ++,
        paintSBM_5: i ++,
        paintSBM_6: i ++,
        paintSBM_7: i ++,
        paintSBM_8: i ++,
        paintSBM_9: i ++,
        paintSBM_10: i ++,
        paintSBM_11: i ++,
        paintSBM_12: i ++,
        paintSBM_13: i ++,
        paintSBM_14: i ++,
        paintSBM_15: i ++,
        paintSBM_16: i ++,
        paintSBM_17: i ++,
        paintSBM_18: i ++,
        paintSBM_19: i ++,
        paintSBM_20: i ++,
        paintSBM_21: i ++,
        paintSBM_22: i ++,
        paintSBM_23: i ++,
        paintSBM_24: i ++,
        paintSBM_25: i ++,
        paintSBM_26: i ++,
        paintSBM_27: i ++,
        paintSBM_28: i ++,
        paintSBM_29: i ++,
        paintSBM_30: i ++,
        paintSBM_31: i ++,
        paintSBM_32: i ++,
        paintSBM_33: i ++,
        paintSBM_34: i ++,
        paintSBM_35: i ++,
        paintSBM_36: i ++,
        paintSBM_37: i ++,
        paintSBM_38: i ++,
        paintSBM_39: i ++,
        paintSBM_40: i ++,
        paintSBM_41: i ++,
        paintSBM_42: i ++,
        paintSBM_43: i ++,
        paintSBM_44: i ++,
        paintSBM_45: i ++,
        paintSBM_46: i ++,
        paintSBM_47: i ++,
        paintSBM_48: i ++,
        paintSBM_49: i ++,
        paintSBM_50: i ++,
        paintSBM_51: i ++,
        paintSBM_52: i ++,
        paintSBM_53: i ++,
        paintSBM_54: i ++,
        paintSBM_55: i ++,
        paintSBM_56: i ++,
        paintSBM_57: i ++,
        paintSBM_58: i ++,
        paintSBM_59: i ++,
        paintSBM_60: i ++,
        paintSBM_61: i ++,
        paintSBM_62: i ++,
        paintSBM_63: i ++,
        paintSBM_64: i ++,
        paintSBM_65: i ++,
        paintSBM_66: i ++,
        paintSBM_67: i ++,
        paintSBM_68: i ++,
        paintSBM_69: i ++,
        paintSBM_70: i ++,
        paintSBM_71: i ++,
        paintSBM_72: i ++,
        paintSBM_73: i ++,
        paintSBM_74: i ++,
        paintSBM_75: i ++,
        paintSBM_76: i ++,
        paintSBM_77: i ++,
        paintSBM_78: i ++,
        paintSBM_79: i ++,
        paintSBM_80: i ++,
        paintSBM_81: i ++,
        paintSBM_82: i ++,
        paintSBM_83: i ++,
        paintSBM_84: i ++,
        paintSBM_85: i ++,
        paintSBM_86: i ++,
        paintSBM_87: i ++,
        paintSBM_88: i ++,
        paintSBM_89: i ++,
        paintSBM_70: i ++,
        paintSBM_91: i ++,
        paintSBM_92: i ++,
        paintSBM_93: i ++,
        paintSBM_94: i ++,
        paintSBM_95: i ++,
        paintSBM_96: i ++,
        paintSBM_97: i ++,
        paintSBM_98: i ++,
        paintSBM_99: i ++,
        paintSBM_100: i ++,
        paintSBM_101: i ++,
        paintSBM_102: i ++,
        paintSBM_103: i ++,
        paintSBM_104: i ++,
        paintSBM_105: i ++,
        paintSBM_106: i ++,
        paintSBM_107: i ++,
        paintSBM_108: i ++,
        paintSBM_109: i ++,
        paintSBM_110: i ++,
        paintSBM_111: i ++,
        paintSBM_112: i ++,
        paintSBM_113: i ++,
        paintSBM_114: i ++,
        paintSBM_115: i ++,
        paintSBM_116: i ++,
        paintSBM_117: i ++,
        paintSBM_118: i ++,
        paintSBM_119: i ++,
        paintSBM_120: i ++,
        paintSBM_121: i ++,
        paintSBM_122: i ++,
        paintSBM_123: i ++,
        paintSBM_124: i ++,
        paintSBM_125: i ++,
        paintSBM_126: i ++,
        paintSBM_127: i ++,
        paintSBM_128: i ++,
        paintSBM_129: i ++,
        paintSBM_130: i ++,
        paintSBM_131: i ++,
        paintSBM_132: i ++,
        paintSBM_133: i ++,
        paintSBM_134: i ++,
        paintSBM_135: i ++,
        paintSBM_136: i ++,
        paintSBM_137: i ++,
        paintSBM_138: i ++,
        paintSBM_139: i ++,
        paintSBM_140: i ++,
        paintSBM_141: i ++,
        paintSBM_142: i ++,
        paintSBM_143: i ++,
        paintSBM_144: i ++,
        paintSBM_145: i ++,
        paintSBM_146: i ++,
        paintSBM_147: i ++,
        paintSBM_148: i ++,
        paintSBM_149: i ++,
        paintSBM_150: i ++,
        paintSBM_151: i ++,
        paintSBM_152: i ++,
        paintSBM_153: i ++,
        paintSBM_154: i ++,
        paintSBM_155: i ++,
        paintSBM_156: i ++,
        paintSBM_157: i ++,
        paintSBM_158: i ++,
        paintSBM_159: i ++,
        paintSBM_160: i ++,
        paintSBM_161: i ++,
        paintSBM_162: i ++,
        paintSBM_163: i ++,
        paintSBM_164: i ++,
        paintSBM_165: i ++,
        paintSBM_166: i ++,
        paintSBM_167: i ++,
        paintSBM_168: i ++,
        paintSBM_169: i ++,
        paintSBM_170: i ++,
        paintSBM_171: i ++,
        paintSBM_172: i ++,
        paintSBM_173: i ++,
        paintSBM_174: i ++,
        paintSBM_175: i ++,
        paintSBM_176: i ++,
        paintSBM_177: i ++,
        paintSBM_178: i ++,
        paintSBM_179: i ++,
        paintSBM_180: i ++,
        paintSBM_181: i ++,
        paintSBM_182: i ++,
        paintSBM_183: i ++,
        paintSBM_184: i ++,
        paintSBM_185: i ++,
        paintSBM_186: i ++,
        paintSBM_187: i ++,
        paintSBM_188: i ++,
        paintSBM_189: i ++,
        paintSBM_170: i ++,
        paintSBM_191: i ++,
        paintSBM_192: i ++,
        paintSBM_193: i ++,
        paintSBM_194: i ++,
        paintSBM_195: i ++,
        paintSBM_196: i ++,
        paintSBM_197: i ++,
        paintSBM_198: i ++,
        paintSBM_199: i ++,
        paintSpecialBrushModeEnd : (i += 80, i++),
        paintSpecialBrushShape: i++,
        paintSpecialBrushShapeEnd : (i += 100, i++),

        paintColPallet: i++,
        paintColImage: i++,
        paintBrushMin : i++,
        paintBrushMax : i++,
        paintPalletPickupPower: i++,
        paintPalletPickupRadius: i++,
        paintCurvePowA: i++,
        paintCurvePowB: i++,
        paintCurvePowC: i++,
        paintCurveStep: i++,
        paintBrushStep: i++,
        paintLengthFade: i++,
        paintWidthFade: i++,
        paintClear: i++,
        paintLogCoordinate: i++,
        paintRandColor: i++,
        paintColorBlend: i++,
        paintBrushSizeBlend: i++,
        paintUseGridGuides: i++,
        paintUseSnapGridGuides: i++,
        paintUseGuidesXY: i++,
        paintUseGuidesXZ: i++,
        paintUseGuidesYZ: i++,
        paintToggleGuidSpaceLock: i++,
        paintToggleGuidSpaceLockX: i++,
        paintToggleGuidSpaceLockY: i++,
        paintToggleGuidSpaceLockZ: i++,
        paintAntiAlias: i++,
        paintPointMode: i++,
        paintCurveMixTypeNone: i++,
        paintCurveMixType1: i++,
        paintCurveMixType2: i++,
        paintCurveMixType3: i++,
        paintCurveMixType4: i++,
        paintCurveMixType5: i++,
        paintCurveMixType6: i++,
        paintCurveMixType7: i++,
        paintCurveMixType8: i++,
        paintCurveMixType9: i++,
        paintCurveMixType10: i++,
        paintCurveMixType11: i++,
        paintCurveMixType12: i++,
        paintCurveMixType13: i++,


        paintCurveMixSource: i++,
        paintCurveDisplayA: i++,
        paintCurveDisplayB: i++,
        paintCurveDisplayC: i++,
        paintCurveLineA: i++,
        paintCurveEaseA: i++,
        paintCurveEase2A: i++,
        paintCurveSigmoid: i++,
        paintCurveBellA: i++,
        paintCurveRandomA: i++,
        paintCurveRandRampA: i++,
        paintCurveWaveA: i++,
        paintCurveRepeatA: i++,
        paintCurveMultiplyA: i++,
        paintCurveInOutA: i++,
        paintBrushOptionsA: i++,
        paintBrushOptionsB: i++,
        paintBrushOptionsC: i++,
        paintBrushOptionsD: i++,
        paintUseDirection: i++,
        paintUseSpeed: i++,
        paintFadeAlphaDist: i++,
        paintSizeDist: i++,
        paintFilterA: i++,
        paintFilterB: i++,
        paintFilterC: i++,
        paintFilterD: i++,
        paintFilterE: i++,
        paintFilterF: i++,
        paintCurveSetBrushColor: i++,
        paintCurveSetBrushAlpha: i++,
        paintCurveSetLineColor: i++,
        paintCurveSetLineWidth: i++,
        paintCurveSetLineAlpha: i++,
        paintCurveSetSprayColor: i++,
        paintCurveSetSpraySize: i++,
        paintCurveSetSpraySpread: i++,
        paintCurveSetSprayAlpha: i++,
        paintCurveSetMarker: i++,
        paintUndo: i++,
        paintRedo: i++,
        paintCut: i++,
        paintCopy: i++,
        paintPaste: i++,
        paintSelectAll: i++,
        paintSelectionOpts: i++,
        paintPasteToImage: i++,
        paintPasteToImageAndWorkSpace: i++,
        paintAsPattern: i++,
        paintClearPattern: i++,
        paintSelectDefinesSprite: i++,
        paintSelectDefinesSpriteAndAddWorkSpace: i++,
        paintSelectAsClip: i++,
        paintCutBufMirV: i++,
        paintCutBufMirH: i++,
        paintCutBufRotCW: i++,
        paintCutBufRotCCW: i++,
        paintCutBufAnimPrev: i++,
        paintCutBufAnimNext: i++,
        paintCutBufUniform: i++,
        paintCutBufWidth: i++,
        paintCutBufHeight: i++,
        paintCoordsToLog: i++,
        paintCoordsToClipboard: i++,
        paintMouseBrushTrackIncrease: i++,
        paintMouseBrushTrackDecrease: i++,
        paintRecordPaintingToggle: i++,
        paintSaveDrawTypeState: i++,
        paintColorMode1: i++,
        paintColorMode2: i++,
        paintColorMode3: i++,
        paintColorMode4: i++,
        paintColorMode5: i++,
        paintColorMode6: i++,
        paintColorMode7: i++,
        paintColorMode8: i++,
        paintColorMode9: i++,
        paintColorMode10: i++,
        paintColorMode11: i++,
        paintColorMode12: i++,
        paintColorMode13: i++,
        paintColorMode14: i++,
        paintColorMode15: i++,
        paintColorMode16: i++,
        paintColorMode17: i++,
        paintColorMode18: i++,
        paintColorMode19: i++,
        paintColorMode20: i++,
        paintColorMode21: i++,
        paintColorMode22: i++,
        paintColorMode23: i++,
        paintColorMode24: i++,
        paintEnd: i++,  // just a marker
        
        animStart: i++,  // just a marker
        animMarksClearSection: i++, // this command can not be issued
        animMarksDeleteSection: i++, // this command can not be issued
        animMarksTrimSection: i++, // this command can not be issued
        animMarksExpandSection: i++, // this command can not be issued
        animMarksContractSection: i++, // this command can not be issued
        animMarksReverseSection: i++, // this command can not be issued
        animGotoStart: i++,
        animGotoEnd: i++,
        animGotoNextFrame: i++,
        animGotoPrevFrame: i++,
        animGotoNextFrameLoop: i++,
        animGotoPrevFrameLoop: i++,
        animGotoNextKey: i++,
        animGotoPrevKey: i++,
        animAddMark: i++,
        animRemoveMark: i++,
        animGotoPrevMark: i++,
        animGotoNextMark: i++,
        animStartTime: i++,
        animEndTime: i++,
        animTime: i++,
        animTimeSlide: i++,
        animTotalTimeSlide: i++,
        animTimeSecondSlider: i++,
        animTimePos: i++,
        animTimeSeg: i++,
        animEditMode: i++,
        animPlayPause: i++,
        animStop: i++,
        animIncreaseFrameStep: i++,
        animFrameStep: i++,
        animDecreaseFrameStep: i++,
        animStoreKeySelection: i++,
        animRecallKeySelection: i++,
        animRemoveAllKeys: i++,
        animRemoveCurrentKeys: i++,
        animRemoveSelectedTracks: i++,
        animMoveKeysLeft: i++,
        animMoveKeysRight: i++,
        animSetTrackLoop: i++,
        animSetTrackLoopOff: i++,
        animSetTrackPingPong: i++,
        animSetTrackReverse: i++,
        animSetTrackForward: i++,
		animSetKeyAll: i++,
        animSetKeyPosScale: i++,
        animSetKeyPos: i++,
        animSetKeyScale: i++,
        animSetKeyRotate: i++,
        animSetKey_x: i++,
        animSetKey_y: i++,
        animSetKey_sx: i++,
        animSetKey_sy: i++,
        animSetKey_rx: i++,
        animSetKey_ry: i++,
        animSetKey_a: i++,
        animSetKey_image: i++,
        animSetKey_rgb: i++,
        animSetKeyEnd : (i += 100, i++),
        animFilterKeyPos: i++,
        animFilterKeyScale: i++,
        animFilterKeyRotate: i++,
        animFilterKey_x: i++,
        animFilterKey_y: i++,
        animFilterKey_sx: i++,
        animFilterKey_sy: i++,
        animFilterKey_rx: i++,
        animFilterKey_ry: i++,
        animFilterKey_a: i++,
        animFilterKey_image: i++,
        animFilterKey_rgb: i++,
        animFilterKeyEnd : (i += 100, i++),

        animSelectAllKeys: i++,
        animSelectAllTracks: i++,
        animSelectInvertTracks: i++,
        animCopySelectedKeys: i++,
        animCutSelectedKeys: i++,
        animPasteSelectedKeys: i++,
        animPasteSelectedKeysAtTime: i++,

        animUpdateUI: i++,
        animTracks: i++,
        animTrackRowSelect: i++,
        animTrackKeySelect: i++,
        animTrackCompactToggle: i++,


        animKeyCurveLinear: i++,
        animKeyCurveEaseOut: i++,
        animKeyCurveEaseInOut: i++,
        animKeyCurveEaseIn: i++,
        animKeyCurveStep: i++,
        animTrackSelectStart: i++,
        animTrackSelectEnd : (i += 100, i++),
        animTrackStart: i++,
        animTrackEnd : (i += 100, i++),
        animEnd: i++,  // just a marker


        spritePannelStart: i++,
        spritePannelEnd: i++,

        //==============================================================================
        test: i++,
        NULL_COMMAND: i++,
        //AA:(()=>setTimeout(()=> log(i),1000))()
    };

})();
