import {Matter} from "../core/Matter.js";

import {Axes} from "../geometry/Axes.js";
Matter.Axes = Axes;
import {Bodies} from "../factory/Bodies.js";
Matter.Bodies = Bodies;
import {Body} from "../body/Body.js";
Matter.Body = Body;
import {Bounds} from "../geometry/Bounds.js";
Matter.Bounds = Bounds;
import {Collision} from "../collision/Collision.js";
Matter.Collision = Collision;
import {Common} from "../core/Common.js";
Matter.Common = Common;
import {Composite} from "../body/Composite.js";
Matter.Composite = Composite;
import {Composites} from "../factory/Composites.js";
Matter.Composites = Composites;
import {Constraint} from "../constraint/Constraint.js";
Matter.Constraint = Constraint;
import {Contact} from "../collision/Contact.js";
Matter.Contact = Contact;
import {Detector} from "../collision/Detector.js";
Matter.Detector = Detector;
import {Engine} from "../core/Engine.js";
Matter.Engine = Engine;
import {Events} from "../core/Events.js";
Matter.Events = Events;
import {Grid} from "../collision/Grid.js";
Matter.Grid = Grid;
import {Mouse, keyboard, keys} from "../core/Mouse.js";
Matter.Mouse = Mouse;
Matter.Keyboard = keyboard;
Matter.Keys = keys;

import {PointConstraint} from "../constraint/PointConstraint.js";
Matter.PointConstraint = PointConstraint;
import {Pair} from "../collision/Pair.js";
Matter.Pair = Pair;
import {Pairs} from "../collision/Pairs.js";
Matter.Pairs = Pairs;
import {Selection} from "../core/Selection.jsm";
Matter.Selection = Selection;
import {Plugin} from "../core/Plugin.js";
Matter.Plugin = Plugin;
import {Query} from "../collision/Query.js";
Matter.Query = Query;
import {Render} from "../render/Render.js";
Matter.Render = Render;
import {Resolver} from "../collision/Resolver.js";
Matter.Resolver = Resolver;
import {Runner} from "../core/Runner.js";
Matter.Runner = Runner;
//import {SAT} from "../collision/SAT.js";
//Matter.SAT = SAT;
import {Sleeping} from "../core/Sleeping.js";
Matter.Sleeping = Sleeping;
import {Svg} from "../geometry/Svg.js";
Matter.Svg = Svg;
import {Vector} from "../geometry/Vector.js";
Matter.Vector = Vector;
import {Vertices} from "../geometry/Vertices.js";
Matter.Vertices = Vertices;
//import {World} from "../body/World.js";
//Matter.World = World;

export {Matter};