const filterGLAvailableFilters = [
    "Filters/lightFilter.js",
    "Filters/exampleFilter.js",
    "Filters/proceduralFilter.js",
    "Filters/convolutionFilter.js",
    "Filters/edgeFilter.js",
    "Filters/displaceFilter.js",
    "Filters/lensDistortFilters.js",
    "Filters/deconvergeFilter.js",
    "Filters/spheroidFilter.js",
    "Filters/warpFilter.js",
    "Filters/hslFilter.js",
    "Filters/thresholdFilter.js",
    "Filters/pointClean.js",
    "Filters/noiseFilter.js",
];